### ISSUE TITLE
Use HTML5 web components for complex controls

### ISSUE THREAD

**Issue by jaigak** [Tropix126/wincss#2]
For controls that doesn't only require style but also functionality, consider using HTML5 web components.

**Comment by tropicaaal** [comment]
I've moved my focus to https://github.com/tropix126/fluent-svelte which provides a much more accurate implimentation of WinUI in svelte. I eventually plan to get svelte's webcomponent built target up and running so it can be used framework-agonistically. Will probably archive this repo.
